all:
	g++ -g -O0 -I../DataAnalyst/DrRobot/Base -I../DataAnalyst/DrRobot/Output -I../DataAnalyst/DrRobot/Plot/gnuplot  main.cpp ../DataAnalyst/DrRobot/Output/LinePlot.cpp ../DataAnalyst/DrRobot/Base/Collection.cpp ../DataAnalyst/DrRobot/Plot/gnuplot/gnuplot_i.c -o plotTester
